// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/page/container.vue')['default']
    Content: typeof import('./src/components/page/content.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/page/footer.vue')['default']
    Fullpage: typeof import('./src/components/fullpage/index.vue')['default']
    Header: typeof import('./src/components/page/header.vue')['default']
    Layout: typeof import('./src/components/page/layout.vue')['default']
    LoadingOverlay: typeof import('./src/components/loading-overlay.vue')['default']
    Main: typeof import('./src/components/page/main.vue')['default']
    Nav: typeof import('./src/components/page/nav.vue')['default']
    Overlay: typeof import('./src/components/loading/overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
    Tabbar: typeof import('./src/components/page/tabbar.vue')['default']
  }
}
